# Generated by Django 6.0.7 on 2026-07-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_OF_SCHOOL', 'Head of School'), ('ADMIN', 'Administrator'), ('LIBRARIAN', 'Librarian'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
