# Generated by Django 6.0.7 on 2026-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_OF_SCHOOL', 'Head of School'), ('ADMIN', 'Administrator'), ('ACADEMIC_MASTER', 'Academic Master'), ('LIBRARIAN', 'Librarian'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('DEPARTMENT_STAFF', 'Department Staff'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
