# Generated by Django 6.0.7 on 2026-08-31 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('sis', '0013_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_OF_SCHOOL', 'Head of School'), ('ADMIN', 'Administrator'), ('LIBRARIAN', 'Librarian'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('HEAD_OF_SCHOOL', 'Head of School'), ('ADMIN', 'Administrator'), ('LIBRARIAN', 'Librarian'), ('REGISTRAR', 'Registrar'), ('ACCOUNTANT', 'Accountant'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sis.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
