# Generated by Django 6.0.7 on 2026-08-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role_alter_userrole_role'),
        ('sis', '0013_staff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('HEAD_OF_SCHOOL', 'Head of School'), ('ADMIN', 'Administrator'), ('ACADEMIC_MASTER', 'Academic Master'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTANT', 'Accountant'), ('DEPARTMENT_STAFF', 'Department Staff'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('is_used', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sis.department')),
            ],
        ),
    ]
