# Generated by Django 6.0.7 on 2026-07-24 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2026', max_length=9, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Form 1', max_length=20, unique=True)),
                ('level', models.CharField(choices=[('O_LEVEL', 'Ordinary Level'), ('A_LEVEL', 'Advanced Level')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(help_text='Used for sorting, e.g. Form 1 = 1, Form 2 = 2 ... Form 6 = 6')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. PCB', max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, help_text='e.g. Physics, Chemistry, Biology', max_length=100)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combinations_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEM1', 'Semester 1'), ('SEM2', 'Semester 2')], max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='sis.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'name'],
                'unique_together': {('academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'A' / 'B' for O-Level, or leave blank for A-Level (uses combination name)", max_length=20)),
                ('class_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streams_managed', to=settings.AUTH_USER_MODEL)),
                ('combination', models.ForeignKey(blank=True, help_text='Only set this for A-Level streams', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='sis.combination')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='sis.schoolclass')),
            ],
            options={
                'ordering': ['school_class__order', 'name'],
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
