# Generated by Django 6.0.7 on 2026-07-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0002_department_guardian_staff_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
