# Generated by Django 6.0.7 on 2026-07-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_guardian_middle_name_student_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g. BIO, PHY, MATH', max_length=20, unique=True)),
                ('levels', models.CharField(choices=[('O_LEVEL', 'Ordinary Level'), ('A_LEVEL', 'Advanced Level'), ('BOTH', 'Both Levels')], default='BOTH', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='sis.department')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'TEACHER'}, related_name='subjects_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
