# Generated by Django 6.0.7 on 2026-07-26 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0004_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='e.g. 131 for Biology (numeric subject code)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='Subject code must contain numbers only.')]),
        ),
    ]
