# Generated by Django 6.0.7 on 2026-07-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_alter_subject_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combination',
            options={'ordering': ['category', 'code']},
        ),
        migrations.AddField(
            model_name='combination',
            name='category',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('ECONOMICS', 'Economics')], default='SCIENCE', max_length=20),
            preserve_default=False,
        ),
    ]
