# Generated by Django 6.0.7 on 2026-07-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0006_alter_combination_options_combination_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='category',
            field=models.CharField(blank=True, choices=[('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('ECONOMICS', 'Economics')], help_text='Only set this for A-Level streams (Science/Arts/Economics)', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sis.combination'),
        ),
    ]
