# Generated by Django 6.0.7 on 2026-07-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0008_remove_stream_class_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='leaving_class',
            field=models.CharField(blank=True, help_text="e.g. 'Form 4' or 'Form 6', set automatically when archived", max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='leaving_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
