# Generated by Django 6.0.7 on 2026-08-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0009_student_leaving_class_student_leaving_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLevelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Science, Arts, ICT, Amali', max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'O-Level Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='olevel_categories',
            field=models.ManyToManyField(blank=True, help_text='Only for O-Level streams - check all categories this stream covers', related_name='streams', to='sis.olevelcategory'),
        ),
    ]
