# Generated by Django 6.0.7 on 2026-08-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_department_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TERM1', 'Term 1'), ('TERM2', 'Term 2')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='sis.semester')),
            ],
            options={
                'ordering': ['semester', 'name'],
                'unique_together': {('semester', 'name')},
            },
        ),
    ]
