# Generated by Django 6.0.7 on 2026-08-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
