# Generated by Django 6.0.7 on 2026-08-24 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_itemcategory_inventoryitem_stockmovement'),
        ('sis', '0013_staff_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a full-semester fee, or select a Term for a single installment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='sis.term'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school_class', 'academic_year', 'semester', 'term')},
        ),
    ]
