# Generated by Django 6.0.7 on 2026-09-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_transaction_department_departmentdemand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='transaction_receipts/'),
        ),
    ]
