# Generated by Django 6.0.7 on 2026-09-14 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sis', '0014_lessonplan_teachingscheduleentry_topic_subtopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Sequence within the day, e.g. 1 = First Period', unique=True)),
                ('label', models.CharField(help_text="e.g. 'First Period', 'Tea Break'", max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_type', models.CharField(choices=[('TEACHING', 'Teaching Period'), ('BREAK', 'Break')], max_length=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='sis.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_assignments', to='sis.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stream__school_class__order', 'stream__name', 'subject__name'],
                'unique_together': {('stream', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('period', models.ForeignKey(limit_choices_to={'period_type': 'TEACHING'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='timetable.period')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='sis.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='sis.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetable.timetable')),
            ],
            options={
                'ordering': ['day', 'period__order'],
                'constraints': [models.UniqueConstraint(fields=('timetable', 'stream', 'day', 'period'), name='unique_stream_slot_per_timetable'), models.UniqueConstraint(fields=('timetable', 'teacher', 'day', 'period'), name='unique_teacher_slot_per_timetable')],
            },
        ),
    ]
